// <auto-generated />
using System;
using ContractManagement.Infrastructure.Persistence.Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContractManagement.Infrastructure.Migrations.Application
{
    [DbContext(typeof(DbDtctechContext))]
    [Migration("20260720043504_Phase6_ContractCoreFoundation")]
    partial class Phase6_ContractCoreFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContractManagement.Infrastructure.Persistence.Application.Models.TblApprovalHistory", b =>
                {
                    b.Property<int>("ApprovalHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApprovalHistoryId"));

                    b.Property<DateTime>("ActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ApprovalAction")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("ApproverEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ObjectId")
                        .HasColumnType("int");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("StepNo")
                        .HasColumnType("int");

                    b.Property<int?>("WorkflowId")
                        .HasColumnType("int");

                    b.HasKey("ApprovalHistoryId")
                        .HasName("PK__tbl_Appr__46B53247FB4F4CF5");

                    b.ToTable("tbl_ApprovalHistory", (string)null);
                });

            modelBuilder.Entity("ContractManagement.Infrastructure.Persistence.Application.Models.TblApprovalWorkflow", b =>
                {
                    b.Property<int>("WorkflowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkflowId"));

                    b.Property<int?>("ApproverEmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("ApproverRoleId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("StepNo")
                        .HasColumnType("int");

                    b.Property<string>("WorkflowName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("WorkflowId")
                        .HasName("PK__tbl_Appr__5704A66A2F3CD2A5");

                    b.ToTable("tbl_ApprovalWorkflow", (string)null);
                });

            modelBuilder.Entity("ContractManagement.Infrastructure.Persistence.Application.Models.TblCategory", b =>
                {
                    b.Property<byte>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte?>("CategoryOrder")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("CategoryParentId")
                        .HasColumnType("tinyint");

                    b.Property<string>("CategoryShortDesc")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Image")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("LangId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.ToTable("tbl_Categories", (string)null);
                });

            modelBuilder.Entity("ContractManagement.Infrastructure.Persistence.Application.Models.TblContract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"));

                    b.Property<string>("ContractCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ContractName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ContractNameEn")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte>("ContractType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())", "DF_tbl_Contract_CreatedDate");

                    b.Property<int>("CreatedEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasDefaultValue("VND")
                        .IsFixedLength();

                    b.Property<int?>("CurrentVersionId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLegacy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte>("LanguageMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<int?>("ParentContractId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("SignDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<int?>("TemplateVersionId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("ContractId");

                    b.HasIndex(new[] { "CurrentVersionId" }, "IX_tbl_Contract_CurrentVersionId");

                    b.HasIndex(new[] { "CustomerId" }, "IX_tbl_Contract_CustomerId");

                    b.HasIndex(new[] { "EmployeeId", "Status" }, "IX_tbl_Contract_EmployeeId_Status");

                    b.HasIndex(new[] { "ParentContractId" }, "IX_tbl_Contract_ParentContractId");

                    b.HasIndex(new[] { "TemplateVersionId" }, "IX_tbl_Contract_TemplateVersionId");

                    b.HasIndex(new[] { "ContractCode" }, "UX_tbl_Contract_ContractCode")
                        .IsUnique()
                        .HasFilter("[ContractCode] IS NOT NULL");

                    b.ToTable("tbl_Contract", null, t =>
                        {
                            t.HasCheckConstraint("CK_tbl_Contract_ContractType", "[ContractType] IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_tbl_Contract_LanguageMode", "[LanguageMode] IN (1, 2)");

                            t.HasCheckConstraint("CK_tbl_Contract_Status", "[Status] IN (0, 1, 2, 3, 4, 5, 6, 7)");

                            t.HasCheckConstraint("CK_tbl_Contract_TotalAmount", "[TotalAmount] >= 0");
                        });
                });

            modelBuilder.Entity("ContractManagement.Infrastructure.Persistence.Application.Models.TblContractAppendix", b =>
                {
                    b.Property<int>("AppendixId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppendixId"));

                    b.Property<string>("AppendixCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("AppendixDate")
                        .HasColumnType("datetime");

                    b.Property<string>("AppendixDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("AppendixName")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("AppendixNameEn")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.HasKey("AppendixId")
                        .HasName("PK__tbl_Cont__44B149C44BC57074");

                    b.ToTable("tbl_ContractAppendix", (string)null);
                });

            modelBuilder.Entity("ContractManagement.Infrastructure.Persistence.Application.Models.TblContractAttachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<string>("ContractFileName")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("ContractFilePath")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<byte>("DocumentType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)99);

                    b.Property<DateTime?>("UploadDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("UploadEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("AttachmentId")
                        .HasName("PK__tbl_Cont__442C64BE6AC2F4CE");

                    b.ToTable("tbl_ContractAttachment", (string)null);
                });

            modelBuilder.Entity("ContractManagement.Infrastructure.Persistence.Application.Models.TblContractTerm", b =>
                {
                    b.Property<int>("TermId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TermId"));

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<int?>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TermContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TermTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("TermId")
                        .HasName("PK__tbl_Cont__410A21A507DB2563");

                    b.ToTable("tbl_ContractTerm", (string)null);
                });

            modelBuilder.Entity("ContractManagement.Infrastructure.Persistence.Application.Models.TblContractVersion", b =>
                {
                    b.Property<int>("VersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VersionId"));

                    b.Property<string>("ChangeNote")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("VersionId")
                        .HasName("PK__tbl_Cont__16C6400F510A7D28");

                    b.ToTable("tbl_ContractVersion", (string)null);
                });

            modelBuilder.Entity("ContractManagement.Infrastructure.Persistence.Application.Models.TblCustomer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("CustomerAccount")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CustomerAddress")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("CustomerBirthday")
                        .HasColumnType("datetime");

                    b.Property<int?>("CustomerCardId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerCareerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerCity")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CustomerCode")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("CustomerComments")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("CustomerCompany")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CustomerCountry")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CustomerFaxNumber")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("CustomerFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerImageIcon")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CustomerMobile")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("CustomerNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("CustomerParentId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerPassword")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<int?>("CustomerPoints")
                        .HasColumnType("int");

                    b.Property<short?>("CustomerRegion")
                        .HasColumnType("smallint");

                    b.Property<int?>("CustomerSourceId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerTaxCode")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("CustomerWebsite")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CustomerZipCode")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())", "DF_tbl_Customers_DateCreated");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime");

                    b.Property<byte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0, "DF_tbl_Customers_Status");

                    b.Property<int?>("UserCreated")
                        .HasColumnType("int");

                    b.Property<int?>("UserModified")
                        .HasColumnType("int");

                    b.HasKey("CustomerId")
                        .HasName("PK__tbl_Cust__A4AE64D84BC5AE01");

                    b.ToTable("tbl_Customers", (string)null);
                });

            modelBuilder.Entity("ContractManagement.Infrastructure.Persistence.Application.Models.TblCustomerInteraction", b =>
                {
                    b.Property<int>("InteractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InteractionId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InteractionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("InteractionSubject")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("InteractionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("NextFollowUpDate")
                        .HasColumnType("datetime");

                    b.HasKey("InteractionId")
                        .HasName("PK__tbl_Cust__922C0496FCECB578");

                    b.ToTable("tbl_CustomerInteraction", (string)null);
                });

            modelBuilder.Entity("ContractManagement.Infrastructure.Persistence.Application.Models.TblDeliveryDetail", b =>
                {
                    b.Property<int>("DeliveryDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryDetailId"));

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("DeliveryDetailId")
                        .HasName("PK__tbl_Deli__EFD2C2E7914C480F");

                    b.ToTable("tbl_DeliveryDetail", (string)null);
                });

            modelBuilder.Entity("ContractManagement.Infrastructure.Persistence.Application.Models.TblDeliveryOrder", b =>
                {
                    b.Property<int>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryId"));

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime");

                    b.Property<string>("DeliveryNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("ReceiverName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReceiverPhone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("DeliveryId")
                        .HasName("PK__tbl_Deli__626D8FCEF0133037");

                    b.ToTable("tbl_DeliveryOrder", (string)null);
                });

            modelBuilder.Entity("ContractManagement.Infrastructure.Persistence.Application.Models.TblDepartment", b =>
                {
                    b.Property<short>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("DepartmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("DepartmentId"));

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("LangId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<byte?>("Stutus")
                        .HasColumnType("tinyint");

                    b.HasKey("DepartmentId")
                        .HasName("PK_Department_DepartmentID");

                    b.ToTable("tbl_Department", (string)null);
                });

            modelBuilder.Entity("ContractManagement.Infrastructure.Persistence.Application.Models.TblEmployee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime");

                    b.Property<string>("DefaultPage")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeAccount")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EmployeeAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EmployeeBirthDate")
                        .HasColumnType("datetime");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("EmployeeEmail")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EmployeeFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeImageIcon")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EmployeeMobile")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("EmployeePassword")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EmployeePhone")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<byte?>("EmployeeType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .IsFixedLength();

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime");

                    b.Property<string>("MaritalStatus")
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .IsFixedLength();

                    b.Property<string>("Others")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<short?>("TitleId")
                        .HasColumnType("smallint");

                    b.Property<int?>("UserCreated")
                        .HasColumnType("int");

                    b.Property<int?>("UserModified")
                        .HasColumnType("int");

                    b.Property<string>("UserRoles")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("WorkTypeId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId")
                        .HasName("PK__tbl_Empl__7AD04F11C415E4E3");

                    b.ToTable("tbl_Employee", (string)null);
                });

            modelBuilder.Entity("ContractManagement.Infrastructure.Persistence.Application.Models.TblFileStorage", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileId"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ObjectId")
                        .HasColumnType("int");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("UploadedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("FileId")
                        .HasName("PK__tbl_File__6F0F98BF777CA8CB");

                    b.ToTable("tbl_FileStorage", (string)null);
                });

            modelBuilder.Entity("ContractManagement.Infrastructure.Persistence.Application.Models.TblInvoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<int?>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("InvoiceStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Unpaid");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.HasKey("InvoiceId")
                        .HasName("PK__tbl_Invo__D796AAB5EDC7461D");

                    b.ToTable("tbl_Invoice", (string)null);
                });

            modelBuilder.Entity("ContractManagement.Infrastructure.Persistence.Application.Models.TblNotification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("NotificationMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("ObjectId")
                        .HasColumnType("int");

                    b.Property<string>("ObjectType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId")
                        .HasName("PK__tbl_Noti__20CF2E127E71675E");

                    b.ToTable("tbl_Notification", (string)null);
                });

            modelBuilder.Entity("ContractManagement.Infrastructure.Persistence.Application.Models.TblOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())", "DF_tbl_Orders_DateCreated");

                    b.Property<DateTime?>("DateExpired")
                        .HasColumnType("datetime");

                    b.Property<string>("NoteFromAdmin")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OrderComment")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<byte?>("OrderStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasComment("0: Pending, 1: Approved")
                        .HasDefaultValue((byte)0, "DF_tbl_Orders_OrderStatus");

                    b.Property<byte?>("OrderType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("UpdatedUser")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.ToTable("tbl_Orders", (string)null);
                });

            modelBuilder.Entity("ContractManagement.Infrastructure.Persistence.Application.Models.TblOrderDetail", b =>
                {
                    b.Property<int>("OrderDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailsId"));

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())", "DF_tbl_OrderDetails_DateCreated");

                    b.Property<DateTime?>("DateExpired")
                        .HasColumnType("datetime");

                    b.Property<double?>("DiscountPercent")
                        .HasColumnType("float");

                    b.Property<short?>("ItemGroupId")
                        .HasColumnType("smallint");

                    b.Property<byte?>("ItemType")
                        .HasColumnType("tinyint");

                    b.Property<string>("NameDetails")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<double?>("OrderQuantity")
                        .HasColumnType("float");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<byte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0, "DF_tbl_OrderDetails_Status");

                    b.Property<double?>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("OrderDetailsId");

                    b.ToTable("tbl_OrderDetails", (string)null);
                });

            modelBuilder.Entity("ContractManagement.Infrastructure.Persistence.Application.Models.TblPayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("PaymentId")
                        .HasName("PK__tbl_Paym__9B556A380D56A7E2");

                    b.ToTable("tbl_Payment", (string)null);
                });

            modelBuilder.Entity("ContractManagement.Infrastructure.Persistence.Application.Models.TblPaymentSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("PaidAmount")
                        .HasColumnType("float");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Pending");

                    b.HasKey("ScheduleId")
                        .HasName("PK__tbl_Paym__9C8A5B49EE0F0668");

                    b.ToTable("tbl_PaymentSchedule", (string)null);
                });

            modelBuilder.Entity("ContractManagement.Infrastructure.Persistence.Application.Models.TblProduct", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Customers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("DisplaySlide")
                        .HasColumnType("tinyint");

                    b.Property<bool?>("GetTrialVersion")
                        .HasColumnType("bit");

                    b.Property<int?>("GoogleClick")
                        .HasColumnType("int");

                    b.Property<byte?>("LangId")
                        .HasColumnType("tinyint");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("MetaKeyword")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Others")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ProductBenefit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("ProductCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())", "DF_tbl_Products_ProductCreatedDate");

                    b.Property<string>("ProductDeployment")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ProductDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDocument")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ProductFeatures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductIconClass")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProductLargeImage")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ProductName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ProductOrder")
                        .HasColumnType("int");

                    b.Property<string>("ProductOverall")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ProductPrice")
                        .HasColumnType("float");

                    b.Property<string>("ProductShortDesc")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ProductShortName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductSlogan")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("ProductSmallImage")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ProductTags")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Rewrite")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("TitleBrowser")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ViewTotal")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("tbl_Products", (string)null);
                });

            modelBuilder.Entity("ContractManagement.Infrastructure.Persistence.Application.Models.TblQuotation", b =>
                {
                    b.Property<int>("QuotationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuotationId"));

                    b.Property<int?>("CreatedEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("QuatationStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Draft");

                    b.Property<DateTime>("QuotationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("QuotationNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("QuotationId")
                        .HasName("PK__tbl_Quot__E19752938F4FC112");

                    b.ToTable("tbl_Quotation", (string)null);
                });

            modelBuilder.Entity("ContractManagement.Infrastructure.Persistence.Application.Models.TblQuotationDetail", b =>
                {
                    b.Property<int>("QuotationDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuotationDetailId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("QuotationId")
                        .HasColumnType("int");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("QuotationDetailId")
                        .HasName("PK__tbl_Quot__0CEE6AE2EC238ED5");

                    b.ToTable("tbl_QuotationDetail", (string)null);
                });

            modelBuilder.Entity("ContractManagement.Infrastructure.Persistence.Application.Models.TblService", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<int?>("Bandwidth")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())", "DF_tbl_Services_DateCreated");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime");

                    b.Property<int?>("DiskStorage")
                        .HasColumnType("int");

                    b.Property<short?>("EmailAccounts")
                        .HasColumnType("smallint");

                    b.Property<int?>("EmailForwarders")
                        .HasColumnType("int");

                    b.Property<byte?>("Ftpaccounts")
                        .HasColumnType("tinyint")
                        .HasColumnName("FTPAccounts");

                    b.Property<bool?>("HasChild")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_tbl_Services_HasChild");

                    b.Property<int?>("LangId")
                        .HasColumnType("int");

                    b.Property<double?>("MaintainPrice")
                        .HasColumnType("float");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("MetaKeyword")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte?>("MsSqlServer")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("MySql")
                        .HasColumnType("tinyint")
                        .HasColumnName("MySQL");

                    b.Property<string>("Others")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("ParkDomain")
                        .HasColumnType("int");

                    b.Property<int?>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Rewrite")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("ServiceContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("ServiceGroupId")
                        .HasColumnType("smallint");

                    b.Property<string>("ServiceImageIcon")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("ServiceOrder")
                        .HasColumnType("int");

                    b.Property<byte?>("ServicePackageId")
                        .HasColumnType("tinyint");

                    b.Property<int?>("ServiceParentId")
                        .HasColumnType("int");

                    b.Property<double?>("ServicePrice")
                        .HasColumnType("float");

                    b.Property<byte?>("ServiceRegion")
                        .HasColumnType("tinyint")
                        .HasComment("1. Tên miền Việt Nam; 2. Tên miền quốc tế");

                    b.Property<string>("ServiceShortDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("ServiceTypeId")
                        .HasColumnType("tinyint")
                        .HasComment("1 - Windows Hosting, 2 - Linux Hosting");

                    b.Property<double?>("SetupPrice")
                        .HasColumnType("float");

                    b.Property<byte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0, "DF_tbl_Services_Status");

                    b.Property<short?>("SubDomain")
                        .HasColumnType("smallint");

                    b.Property<string>("TitleBrowser")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UserCreated")
                        .HasColumnType("int");

                    b.Property<int?>("UserModified")
                        .HasColumnType("int");

                    b.HasKey("ServiceId")
                        .HasName("PK__tbl_Serv__C51BB00A20C1E124");

                    b.ToTable("tbl_Services", (string)null);
                });

            modelBuilder.Entity("ContractManagement.Infrastructure.Persistence.Application.Models.TblServiceType", b =>
                {
                    b.Property<byte>("ServiceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("ServiceTypeId"));

                    b.Property<byte?>("LangId")
                        .HasColumnType("tinyint");

                    b.Property<string>("ServiceTypeName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ServiceTypeId");

                    b.ToTable("tbl_ServiceTypes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
